apiVersion: apps/v1
kind: Deployment
metadata:
  name: evezy
  labels:
    app: evezy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evezy
  template:
    metadata:
      labels:
        app: evezy
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: evezy
        image: maddie2030/evezy-v1:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80