apiVersion: apps/v1
kind: Deployment
metadata:
  name: evezy-v1
  labels:
    app: evezy-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evezy-v1
  template:
    metadata:
      labels:
        app: evezy-v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: evezy-v1
        image: maddie2030/evezy-v1:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4000